version: "3"
services:
  db:
    image: "postgres:12-alpine"
    container_name: "datadoor"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: 'pasha_ddoor_db'
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: 'postgres'
    volumes:
      - pasha_news_data:/var/lib/postgresql/data
      -       ./scripts:/scripts
volumes:
  pasha_news_data:
